### ISSUE TITLE
Could not find module

### ISSUE THREAD

**Issue by Ligerx** [mike-north/ember-anchor#2]
Hi, this is my first time making an issue, so go easy on me!

So I installed the project through npm and got this error. Then I also tried to install it with bower and still got the same error. I'm on ember cli 1.13.1.

`Error: Could not find module 'ember-new-computed' imported from 'ember-anchor/mixins/controller-support'`

**Comment by truenorth** [comment]
I'll fix this in the blueprint. For now, just run 
```
ember install ember-new-computed
```
and you should be good to go
