### ISSUE TITLE
Ember Anchor not working with Firefox and IE but works with Chrome

### ISSUE THREAD

**Issue by sharmaomkar** [mike-north/ember-anchor#46]
Hi I tried this ember anchor addon and found working in Chrome but not in Firefox and IE. Am I missing something ? Here is my sample app link : [code link](https://github.com/sharmaomkar/ember-anchor-demo)

**Comment by sharmaomkar** [comment]
Demo is not working in Firefox and in Internet Explorer. I have used this addon in a tool and works fine with chrome but not in Firefox and in IE. Any help on this ??

**Comment by mike-north** [comment]
This has been fixed
